console.log('Hello World');
console.log('Hello World');
var item = 'elemento';
var item2 = 'elemento2';
var num = 'Numero';
var booleano;
booleano = true;
var numero;
numero = 4;
var str1;
str1 = 'Hola bon dia';
var modulos;
modulos = ['hola', true, 7];
var new1;
new1 = 5;
new1 = true;
